/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    404: typeof import('./src/views/common/error/404.vue')['default']
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABadge: typeof import('ant-design-vue/es')['Badge']
    ABreadcrumb: typeof import('ant-design-vue/es')['Breadcrumb']
    ABreadcrumbItem: typeof import('ant-design-vue/es')['BreadcrumbItem']
    AButton: typeof import('ant-design-vue/es')['Button']
    AccountRecordInfo: typeof import('./src/views/finance/accountRecordInfo/index.vue')['default']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    BarChart: typeof import('./src/views/finance/financeAnalysis/chart/barChart.vue')['default']
    Breadcrumb: typeof import('./src/layout/components/breadcrumb/index.vue')['default']
    Chart: typeof import('./src/views/model/chart/index.vue')['default']
    Dashboard: typeof import('./src/views/dashboard/index.vue')['default']
    Dict: typeof import('./src/views/finance/dict/index.vue')['default']
    FinanceAnalysis: typeof import('./src/views/finance/financeAnalysis/index.vue')['default']
    FinanceManager: typeof import('./src/views/finance/financeManager/index.vue')['default']
    Layout: typeof import('./src/layout/index.vue')['default']
    LineChart: typeof import('./src/views/finance/financeAnalysis/chart/lineChart.vue')['default']
    Login: typeof import('./src/views/login/index.vue')['default']
    Menu: typeof import('./src/layout/components/navbar/menu.vue')['default']
    MyUpload: typeof import('./src/views/components/myUpload.vue')['default']
    Navbar: typeof import('./src/layout/components/navbar/index.vue')['default']
    Order: typeof import('./src/views/order/order/index.vue')['default']
    PieChart: typeof import('./src/views/finance/financeAnalysis/chart/pieChart.vue')['default']
    PmsAttr: typeof import('./src/views/product/pmsAttr/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Seckill: typeof import('./src/views/seckill/seckill/index.vue')['default']
    SvgIcon: typeof import('./src/views/common/icons/svgIcon.vue')['default']
    UserManager: typeof import('./src/views/user/userManager/index.vue')['default']
  }
}
